###########################################################
# GCC template makefile
###########################################################


SELECT_CHAPTER_SOURCES = 
SELECT_CHAPTER_SOURCES += SelectChapter.c

C_SUBINC += $(TOP)/chapter

SRCS += $(SELECT_CHAPTER_SOURCES)